import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./layout.css"
import Navigator from "./components/Navigator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="MainContainer">
          <div className="TitleContainer">
            <h1>Pagina que llama a cosas de Ricardo y Mortirio API de nuevo como no</h1>
          </div>
          
          <Navigator/>
          {children}   
        </div>   
      </body>
    </html>
  );
}
